### ISSUE TITLE
Crash onDestroy of the activity, no NavController attached

### ISSUE THREAD

**Issue by JRaadPro** [beetlestance/android-extensions#3]
Hello, 

I am having a weird bug when using primary fragment. 
When going back to exit the app, an exception is thrown saying the activity can not be destroyed because it doesn't have a NavController attached

Here is the crash
`java.lang.RuntimeException: Unable to destroy activity {com.proximie.app.dev/com.proximie.app.main.MainActivity}: java.lang.IllegalStateException: View androidx.fragment.app.FragmentContainerView{43f5a1d V.E...... ......ID 0,0-1080,1840 #7f080126 app:id/nav_host_fragment} does not have a NavController set
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5111)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: View androidx.fragment.app.FragmentContainerView{43f5a1d V.E...... ......ID 0,0-1080,1840 #7f080126 app:id/nav_host_fragment} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:84)
        at androidx.navigation.fragment.NavHostFragment.onDestroyView(NavHostFragment.java:388)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3171)
        at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:726)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:360)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:512)
        at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:243)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3113)
        at androidx.fragment.app.FragmentManager.dispatchDestroyView(FragmentManager.java:3081)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3165)
        at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:726)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:360)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:512)
        at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:243)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3113)
        at androidx.fragment.app.FragmentManager.dispatchDestroyView(FragmentManager.java:3081)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3165)
        at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:726)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:360)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3109)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3088)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:322)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
        at com.proximie.app.main.MainActivity.onDestroy(MainActivity.kt:33)
        at android.app.Activity.performDestroy(Activity.java:8245)
2021-01-30 11:11:54.864 13695-13695/com.proximie.app.dev E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
        	... 11 more`

My activity is so simple, i used the samples
`
   class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.AppTheme)
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setUpDeeplinkNavigationBehavior(
            navHostFragmentId = R.id.nav_host_activity,
            primaryFragmentId = R.id.fragmentMain,
            graphId = R.navigation.graph_root,
        )
        handleDeeplinkIntent()
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        setIntent(intent)
        handleDeeplinkIntent()
    }

    override fun onDestroy() {
        super.onDestroy()
        Timber.w("DESTROYED")
    }
}
   `

**Comment by kameshyadavky** [comment]
Which version of the navigation library are you using? Can you provide a link to the sample?
